# Generated by Django 3.1.2 on 2020-11-10 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("emailtemplates", "0005_auto_20201110_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="modified"
            ),
        ),
    ]
