# Generated by Django 3.1.13 on 2022-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailtemplates", "0010_auto_20220803_1419"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "ordering": ("ordering",),
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="ordering",
            field=models.PositiveIntegerField(default=1, verbose_name="ordering"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="you can use variables from table",
                max_length=255,
                verbose_name="subject",
            ),
        ),
    ]
