# Generated by Django 3.1.13 on 2022-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailtemplates", "0011_auto_20221026_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="attachment_file",
            field=models.FileField(
                max_length=255,
                upload_to="emails/attachments/",
                verbose_name="Attachment file",
            ),
        ),
        migrations.AlterField(
            model_name="massemailattachment",
            name="attachment_file",
            field=models.FileField(
                max_length=255,
                upload_to="emails/attachments/",
                verbose_name="Attachment file",
            ),
        ),
    ]
