# Generated by Django 5.1.6 on 2026-09-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailtemplates", "0012_auto_20221103_1506"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "header_content",
                    models.TextField(
                        blank=True,
                        help_text="Rendered above the content of every email template using this layout.",
                        verbose_name="header content",
                    ),
                ),
                (
                    "footer_content",
                    models.TextField(
                        blank=True,
                        help_text="Rendered below the content of every email template using this layout.",
                        verbose_name="footer content",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
            ],
            options={
                "verbose_name": "Email layout",
                "verbose_name_plural": "Email layouts",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. When set, the content above is rendered between the header and the footer of the chosen layout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_templates",
                to="emailtemplates.emaillayout",
                verbose_name="layout",
            ),
        ),
    ]
