# Generated by Django 5.1.6 on 2026-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailtemplates", "0013_emaillayout_emailtemplate_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillayout",
            name="styles",
            field=models.TextField(
                blank=True,
                help_text="Plain CSS, without the &lt;style&gt; tag - it is added automatically and placed before the header.",
                verbose_name="CSS styles",
            ),
        ),
    ]
